### ISSUE TITLE
AppImage Release

### ISSUE THREAD

**Issue by pktiuk** [juliagoda/antimicroX#128]
I have created Workflow creating AppImage file (allows running antimicroX on multiple linux distributions without installation).
It is published here
https://github.com/pktiuk/antimicroX/releases/tag/AppimageTestv2
My working branch:
https://github.com/pktiuk/antimicroX/tree/building_appimage

I think that before opening Pull Request i think it would be good to test it on other distributions of linux.

I have tested it on debian based: Ubuntu 20.04, Ubuntu 18.04 and linux Mint 19.1
It would be good if someone would check it on Fedora-based or Arch-based linux.

To check if does it work just:
```
wget https://github.com/pktiuk/antimicroX/releases/download/AppimageTest/antimicroX-x86_64.AppImage
chmod +x antimicroX-x86_64.AppImage
./antimicroX-x86_64.AppImage
```
And then report if does it work on your system.

Current status of issue:
- [x] add workflow building AppImage on release
- [x] check if build works on multiple systems
- [x]  add to README building instruction for AppImage
- [x] add update info to package
- [ ] (optional) add AntimicroX to [AppImageHub](https://appimage.github.io/apps/)

**Comment by pktiuk** [comment]
@juliagoda Tags fitting this issue: `help wanted`, `good first issue`, `enchancement`

**Comment by juliagoda** [comment]
Okay, just let me catch my breath, because I'm doing something else temporarily

**Comment by pktiuk** [comment]
Don't worry, we don't have any deadlines.
Take your time. :smile:

**Comment by juliagoda** [comment]
Ok it works on Arch Linux

**Comment by pktiuk** [comment]
Good, today i have finished updating mechanism. Everything is ready to merge
https://github.com/juliagoda/antimicroX/pull/129

Later I will add AntimicroX to AppImageHub

**Comment by pktiuk** [comment]
One of requirements to add our app to AppImageHub is having version compatibile with Ubuntu 16.04 (the oldest still-supported Ubuntu LTS release), but AntiMicroX doesn't compile on Ubuntu 16.04
```
[ 39%] Building CXX object CMakeFiles/antilib.dir/src/moc_calibration.cpp.o
In file included from /home/runner/work/antimicroX/antimicroX/src/joycontrolstick.h:23:0,
                 from /home/runner/work/antimicroX/antimicroX/build/src/../../src/uihelpers/joycontrolstickeditdialoghelper.h:23,
                 from /home/runner/work/antimicroX/antimicroX/build/src/../../src/joycontrolstickeditdialog.h:23,
                 from /home/runner/work/antimicroX/antimicroX/build/src/../../src/calibration.h:22,
                 from /home/runner/work/antimicroX/antimicroX/build/src/moc_calibration.cpp:9:
/home/runner/work/antimicroX/antimicroX/src/joybutton.h:34:26: fatal error: QDeadlineTimer: No such file or directory
compilation terminated.
CMakeFiles/antilib.dir/build.make:842: recipe for target 'CMakeFiles/antilib.dir/src/moc_calibration.cpp.o' failed
make[2]: *** [CMakeFiles/antilib.dir/src/moc_calibration.cpp.o] Error 1
make[1]: *** [CMakeFiles/antilib.dir/all] Error 2
CMakeFiles/Makefile2:182: recipe for target 'CMakeFiles/antilib.dir/all' failed
make: *** [all] Error 2
```
Full log available [here](https://github.com/pktiuk/antimicroX/runs/835214524?check_suite_focus=true)

**Comment by pktiuk** [comment]
@juliagoda 
Maybe you should draft new (at least minor or pre-) release, just to build an AppImage and make it accessible for users?

You could also grab and add AppImage from [my repo](https://github.com/pktiuk/antimicroX/releases/tag/First_AppImage) to resources, if you don't want to publish new release yet. 

I am talking in context of this issue: https://github.com/juliagoda/antimicroX/issues/147

**Comment by pktiuk** [comment]
Because of ending maintenance of AntiMicroX on this repository further submitting `AppImage` release to AppImageHub will now be tracked in new AntiMicroX repository via issue: https://github.com/AntiMicroX/antimicroX/issues/2
